SELECT 
    *
FROM
    clean_data;
    
 ##### Total Revenue #####
 SELECT 
    SUM(purchase_amount) AS total_revenue
FROM
    clean_data;
    
##### Sales by Category #####
SELECT 
    category, SUM(purchase_amount)
FROM
    clean_data
GROUP BY category;  

##### Top Payment Methods #####
SELECT 
    payment_method, COUNT(*)
FROM
    clean_data
GROUP BY payment_method;

##### Average Rating by Category #####
SELECT 
    category, AVG(review_rating)
FROM
    clean_data
GROUP BY category;

#--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    clean_data
GROUP BY gender;

#--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, purchase_amount
FROM
    clean_data
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            clean_data);
 
#--Q3. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM clean_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#--Q4. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM clean_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
 
#--Q5. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM clean_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#--Q6. Which location generates the highest revenue?
SELECT 
    location, ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    clean_data
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;

#--Q7. What is the monthly/seasonal sales trend?
SELECT 
    season,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount), 2) AS revenue
FROM
    clean_data
GROUP BY season
ORDER BY revenue DESC;

#--Q8. Which payment method generates the highest revenue?
SELECT 
    payment_method,
    COUNT(*) AS total_transactions,
    ROUND(SUM(purchase_amount), 2) AS revenue
FROM
    clean_data
GROUP BY payment_method
ORDER BY revenue DESC;

#--Q9. Identify high-value customers (Top 10 spenders)?
SELECT 
    customer_id, ROUND(SUM(purchase_amount), 2) AS total_spent
FROM
    clean_data
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

#--Q10. Which category has the highest repeat purchase behavior?
SELECT category,
       COUNT(*) AS total_orders,
       SUM(CASE WHEN previous_purchases > 1 THEN 1 ELSE 0 END) AS repeat_orders,
       ROUND(100.0 * SUM(CASE WHEN previous_purchases > 1 THEN 1 ELSE 0 END)/COUNT(*),2) AS repeat_rate
FROM clean_data
GROUP BY category
ORDER BY repeat_rate DESC;





 









    
    